import type { Metadata } from 'next';
import { Zen_Antique } from 'next/font/google';
import { Suspense } from 'react';
import Loading from './loading';
import './globals.css';

const zen = Zen_Antique({
  weight: '400',
  display: 'swap',
  preload: false,
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'NextJS-AppRouter-SWR-AuthJS-with-Prisma-PlanetScale-MySQL-App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={zen.className}>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
